global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'system-nginx'
    metrics_path: /metrics
    static_configs:
      - targets: [ '87.239.106.139:9100' ]

  - job_name: 'system-ubuntu-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['89.208.229.65:9100']

  - job_name: 'system-ubuntu-2'
    metrics_path: /metrics
    static_configs:
      - targets: [ '87.239.108.188:9100' ]

  - job_name: 'system-ubuntu-3'
    metrics_path: /metrics
    static_configs:
      - targets: [ '87.239.108.234:9100' ]

  - job_name: 'ubuntu-1'
    metrics_path: /metrics
    static_configs:
      - targets: ['89.208.229.65:9090']

  - job_name: 'ubuntu-2'
    metrics_path: /metrics
    static_configs:
      - targets: ['87.239.108.188:9090']

  - job_name: 'ubuntu-3'
    metrics_path: /metrics
    static_configs:
      - targets: ['87.239.108.234:9090']

